name: Deploy Vue Project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Change directory to vue-project
        run: cd vue-project

      - name: Install dependencies
        run: npm install
        working-directory: ./vue-project

      - name: Run build
        run: npm run build
        working-directory: ./vue-project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue-project/dist
